import fs from "fs-extra";
import path from "path";

export async function generateLookbookPage(): Promise<string[]> {
  // Minimalny generator: tworzy stronę /lookbook (Next app/pages – wykryjemy oba)
  // process.cwd() zwraca root repo, więc ścieżka jest względna
  // Jeśli jesteśmy w bots/orchestrator, cofnij się do roota
  let root = process.cwd();
  if (root.endsWith("bots\\orchestrator") || root.endsWith("bots/orchestrator")) {
    root = path.join(root, "..", "..");
  }
  const appRoute = path.join(root, "apps", "web", "app", "lookbook", "page.tsx");
  const pagesRoute = path.join(root, "apps", "web", "pages", "lookbook.tsx");

  const content = `export default function LookbookPage(){
  return (
    <main style={{padding:'2rem'}}>
      <h1>FFDH Lookbook</h1>
      <p>Minimal stub generated by CodeBot.</p>
    </main>
  );
}
`;

  // Check if app/ directory exists (App Router)
  if (await fs.pathExists(path.join(root, "apps", "web", "app"))) {
    await fs.ensureDir(path.dirname(appRoute));
    await fs.writeFile(appRoute, content, "utf8");
    return [appRoute];
  } else if (await fs.pathExists(path.join(root, "apps", "web", "pages"))) {
    // Pages Router
    await fs.ensureDir(path.dirname(pagesRoute));
    await fs.writeFile(pagesRoute, content, "utf8");
    return [pagesRoute];
  } else {
    // Default to app/ (App Router)
    await fs.ensureDir(path.dirname(appRoute));
    await fs.writeFile(appRoute, content, "utf8");
    return [appRoute];
  }
}

