# Create .env.local for development
@"
# FFDH Environment Variables - Development
# DO NOT COMMIT REAL SECRETS. PLACEHOLDERS ONLY.

NEXT_PUBLIC_SANITY_PROJECT_ID=YOUR_SANITY_PROJECT_ID
NEXT_PUBLIC_SANITY_DATASET=production
SANITY_AUTH_TOKEN=YOUR_SANITY_AUTH_TOKEN

NEXT_PUBLIC_SUPABASE_URL=YOUR_SUPABASE_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=YOUR_SUPABASE_ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=YOUR_SUPABASE_SERVICE_ROLE_KEY

NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=YOUR_STRIPE_PUBLISHABLE_KEY
STRIPE_SECRET_KEY=YOUR_STRIPE_SECRET_KEY
STRIPE_WEBHOOK_SECRET=YOUR_STRIPE_WEBHOOK_SECRET

OPENAI_API_KEY=YOUR_OPENAI_API_KEY

ENABLE_SIGNATURE_CHECK=false
"@ | Out-File -FilePath .env.local -Encoding utf8

# Create .env.production.local
@"
# FFDH Environment Variables - Production
# DO NOT COMMIT REAL SECRETS. Set in Vercel Dashboard.

NEXT_PUBLIC_SANITY_PROJECT_ID=YOUR_SANITY_PROJECT_ID
NEXT_PUBLIC_SANITY_DATASET=production
SANITY_AUTH_TOKEN=YOUR_SANITY_AUTH_TOKEN

NEXT_PUBLIC_SUPABASE_URL=YOUR_SUPABASE_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=YOUR_SUPABASE_ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=YOUR_SUPABASE_SERVICE_ROLE_KEY

NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=YOUR_STRIPE_PUBLISHABLE_KEY
STRIPE_SECRET_KEY=YOUR_STRIPE_SECRET_KEY
STRIPE_WEBHOOK_SECRET=YOUR_STRIPE_WEBHOOK_SECRET

OPENAI_API_KEY=YOUR_OPENAI_API_KEY

ENABLE_SIGNATURE_CHECK=true
NODE_ENV=production
NEXT_PUBLIC_APP_URL=https://your-app-url.example
NEXT_PUBLIC_APP_NAME=FFDH
"@ | Out-File -FilePath .env.production.local -Encoding utf8

Write-Host "✅ Created .env.local and .env.production.local"

